# Generated by Django 6.0.3 on 2026-05-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='text',
            new_name='review',
        ),
    ]
